// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_motif_positions
List get_motif_positions(List& mats, const std::vector<std::string> x, const std::vector<double> nuc_freqs, const double E, const size_t w);
RcppExport SEXP _TFCookbook_get_motif_positions(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP ESEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type nuc_freqs(nuc_freqsSEXP);
    Rcpp::traits::input_parameter< const double >::type E(ESEXP);
    Rcpp::traits::input_parameter< const size_t >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(get_motif_positions(mats, x, nuc_freqs, E, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TFCookbook_get_motif_positions", (DL_FUNC) &_TFCookbook_get_motif_positions, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_TFCookbook(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
