# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.get_motif_positions <- function(mats, x, nuc_freqs, E, w) {
    .Call(`_TFCookbook_get_motif_positions`, mats, x, nuc_freqs, E, w)
}

